#ifndef COMMANDS_H_YMC65IJY
#define COMMANDS_H_YMC65IJY

enum HostCommand 
{
	HOST_CMD_VERSION = 0,
	HOST_CMD_INIT = 1,
	HOST_CMD_GET_BUFFER_SIZE = 2,
	HOST_CMD_CLEAR_BUFFER = 3,
	HOST_CMD_GET_POSITION = 4,
	HOST_CMD_GET_RANGE = 5,
	HOST_CMD_SET_RANGE = 6,
	HOST_CMD_ABORT = 7,
	HOST_CMD_PAUSE = 8,
	HOST_CMD_PROBE = 9,
	HOST_CMD_TOOL_QUERY = 10,
	HOST_CMD_IS_FINISHED = 11,
	HOST_CMD_READ_EEPROM = 12,
	HOST_CMD_WRITE_EEPROM = 13,
	
	HOST_CMD_DEBUG = 0x7e,
	
};

enum HostReply {
	HOST_REPLY_OK = 0,
	HOST_REPLY_INVALID_CRC = 1,
	HOST_REPLY_TIMEOUT = 2,
};


#endif /* end of include guard: COMMANDS_H_YMC65IJY */



